language: node_js
node_js:
  - node
branches:
  only:
    - master
script:
  - npm install ftp
  - npm install chalk
deploy:
  skip_cleanup: true
  provider: script
  script: 'find ./ -type f -exec curl -u $FTP_USERNAME:$FTP_PASSWORD --ftp-create-dirs -T {} ftp://ftp.scub.net/www/{} ";"'
  on:
    branch: master
