language: java
install: true
addons:
  apt:
    packages:
    - lftp
    - libssl-dev
branches:
  only:
  - master
script:
# Upload website.
- cd $TRAVIS_BUILD_DIR/public/
- lftp -e "mirror -R ./ /home/scub/www/ ; quit" -u $FTP_USERNAME,$FTP_PASSWORD sftp://ftp.scub.net

