language: node_js
node_js:
  - node
branches:
  only:
    - master
script:
  - npm version
deploy:
  skip_cleanup: true
  provider: script
  script: 
    - npm install ftp
    - node deploy.js
  on:
    branch: master
